"""HMAC signing for workspace-file URLs.

Artifacts generated by run_python live in a shared temp dir and are served over
an unauthenticated static endpoint (so the browser can render them inline via
<img>). To stop anyone from downloading another session's artifact by guessing
its filename, each served URL carries an HMAC signature over its relative path.
"""

from __future__ import annotations

import hashlib
import hmac

from app.core.config import settings


def _secret() -> bytes:
    # Reuse the app signing secret. A stable dev-only fallback is fine because
    # signature checks are only enforced in production (see serve_workspace_file).
    secret = settings.JWT_SECRET or settings.ENCRYPTION_KEY
    if not secret:
        if settings.is_production:
            raise RuntimeError("JWT_SECRET or ENCRYPTION_KEY required to sign workspace URLs")
        secret = "atelier-workspace-dev"
    return secret.encode()


def sign_path(rel_path: str) -> str:
    """Return a hex HMAC-SHA256 signature for a workspace-relative path."""
    return hmac.new(_secret(), rel_path.encode(), hashlib.sha256).hexdigest()


def verify_path(rel_path: str, sig: str | None) -> bool:
    """Constant-time check that `sig` matches `rel_path`."""
    if not sig:
        return False
    return hmac.compare_digest(sign_path(rel_path), sig)
